TCCAPP/Controllers/BuyersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CORE;
using MarketingCORE.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace MarketingCORE.Controllers
{
    [Authorize(Roles = "USER")]
    public class BuyersController : Controller
    {
        private readonly MarketingCOREContext _context;

        public BuyersController(MarketingCOREContext context)
        {
            _context = context;
        }

        // GET: Buyers
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Buyer.ToListAsync());
        //}

        public async Task<IActionResult> Index(int edad, string genero, float ingresos, string geo)
        {
            List<Buyer> productList = await _context.Buyer.ToListAsync();

            List<Buyer> filteredList = productList;

            if (!string.IsNullOrEmpty(edad.ToString()) && edad != 0)
            {
                filteredList = filteredList.Where(p => p.Edad == edad).ToList();
            }

            if (!string.IsNullOrEmpty(genero))
            {
                filteredList = filteredList.Where(p => p.Genero.Contains(genero)).ToList();
            }

            if (!string.IsNullOrEmpty(ingresos.ToString()) && ingresos != 0)
            {
                filteredList = filteredList.Where(p => p.Ingresos == ingresos).ToList();
            }
            if (!string.IsNullOrEmpty(geo))
            {
                filteredList = filteredList.Where(p => p.Geografia.Contains(geo)).ToList();
            }

            ViewBag.edad = edad;
            ViewBag.genero = genero;
            ViewBag.ingresos = ingresos;
            ViewBag.geo = geo;

            return View(filteredList);
        }


        // GET: Buyers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Buyers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Edad,Genero,Ingresos,Intereses,Frustraciones,Geografia")] Buyer buyer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buyer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(buyer);
        }


        private bool BuyerExists(int id)
        {
            return _context.Buyer.Any(e => e.Id == id);
        }
    }
}

TCCAPP/Controllers/CampanasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CORE;
using MarketingCORE.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace MarketingCORE.Controllers
{
    [Authorize(Roles = "USER")]
    public class CampanasController : Controller
    {
        private readonly MarketingCOREContext _context;

        public CampanasController(MarketingCOREContext context)
        {
            _context = context;
        }

        // GET: Campanas

        public async Task<IActionResult> Index(string objetivo, string canal, string buyer)
        {
            List<Campana> productList = await _context.Campana.ToListAsync();
            List<Buyer> buyersList = await _context.Buyer.ToListAsync();
            List<campanaView> filteredList = new List<campanaView>();
            foreach (Campana c in productList)
            {
                Buyer b = buyersList.Where(p => p.Id==c.BuyerID).ToList().First();
                filteredList.Add(new campanaView { buyer=b, campana=c});
            }

            if (!string.IsNullOrEmpty(objetivo))
            {
                filteredList = filteredList.Where(p => p.campana.Objetivo.Equals(objetivo)).ToList();
            }

            if (!string.IsNullOrEmpty(canal))
            {
                filteredList = filteredList.Where(p => p.campana.Canal.Equals(canal)).ToList();
            }

            if (!string.IsNullOrEmpty(buyer))
            {
                filteredList = filteredList.Where(p => p.buyer.Nombre.Equals(buyer)).ToList();
            }

            ViewBag.objetivo = objetivo;
            ViewBag.canal = canal;
            ViewBag.buyer = buyer;

            return View(filteredList);
        }


        // GET: Campanas/Create
        public async Task<IActionResult> Create()
        {
            campanaView modelo = new campanaView();
            List<Buyer> buyersList = await _context.Buyer.ToListAsync();
            
            modelo.opNomBuy = new List<SelectListItem>();
            foreach (Buyer b in buyersList)
            {
                modelo.opNomBuy.Add(new SelectListItem { Value = b.Id.ToString(), Text = b.Nombre });
            }
            
   
            return View(modelo);
        }

        // POST: Campanas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Objetivo,Canal,Presupuesto,Frecuencia,BuyerID,UserID,fechaInicio, fechaVencimiento")] Campana campana)
        {
            if (ModelState.IsValid)
            {
                var usuarioAct = HttpContext.User.Identity.Name;
                List<Usuario> us = await _context.Usuario.ToListAsync();
                Usuario usl = us.Where(p => p.Nombre.Equals(usuarioAct)).ToList().First();
                campana.UserID =usl.Id;
                _context.Add(campana);
                await _context.SaveChangesAsync();
                string url = Url.Action("Create", "KPIXCampanas", campana);
                return Redirect(url);

            }
            return View(campana);
        }
        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            return View(id);
        }
        // GET: Campanas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Campana == null)
            {
                return NotFound();
            }

            var campana = await _context.Campana
                .FirstOrDefaultAsync(m => m.Id == id);
            if (campana == null)
            {
                return NotFound();
            }

            return View(campana);
        }

        // POST: Campanas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Campana == null)
            {
                return Problem("Entity set 'MarketingCOREContext.Campana'  is null.");
            }
            var campana = await _context.Campana.FindAsync(id);
            if (campana != null)
            {
                List<KPIXCampana> valor=await _context.KPIXCampana.ToListAsync();
                List<KPIXCampana> limpiar= valor.Where(x => x.CampanaID == campana.Id).ToList();
                _context.Campana.Remove(campana);
                foreach(KPIXCampana a in limpiar)
                {
                    _context.KPIXCampana.Remove(a);
                }
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampanaExists(int id)
        {
          return _context.Campana.Any(e => e.Id == id);
        }
    }
}

TCCAPP/Controllers/KPIsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CORE;
using MarketingCORE.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace MarketingCORE.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class KPIsController : Controller
    {
        private readonly MarketingCOREContext _context;

        public KPIsController(MarketingCOREContext context)
        {
            _context = context;
        }

        // GET: KPIs
        public async Task<IActionResult> Index()
        {
              return View(await _context.KPI.ToListAsync());
        }

        // GET: KPIs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.KPI == null)
            {
                return NotFound();
            }

            var kPI = await _context.KPI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kPI == null)
            {
                return NotFound();
            }

            return View(kPI);
        }

        // GET: KPIs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KPIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion")] KPI kPI)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kPI);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kPI);
        }

        // GET: KPIs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.KPI == null)
            {
                return NotFound();
            }

            var kPI = await _context.KPI.FindAsync(id);
            if (kPI == null)
            {
                return NotFound();
            }
            return View(kPI);
        }

        // POST: KPIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion")] KPI kPI)
        {
            if (id != kPI.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kPI);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KPIExists(kPI.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kPI);
        }

        // GET: KPIs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.KPI == null)
            {
                return NotFound();
            }

            var kPI = await _context.KPI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kPI == null)
            {
                return NotFound();
            }

            return View(kPI);
        }

        // POST: KPIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.KPI == null)
            {
                return Problem("Entity set 'MarketingCOREContext.KPI'  is null.");
            }
            var kPI = await _context.KPI.FindAsync(id);
            if (kPI != null)
            {
                _context.KPI.Remove(kPI);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KPIExists(int id)
        {
          return _context.KPI.Any(e => e.Id == id);
        }
    }
}

TCCAPP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - TCCAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TCCAPP.styles.css" asp-append-version="true" />
</head>
<body style="background-color:lightcyan">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SERVIDOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("USER"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Buyers" asp-action="Index">Gestionar Buyers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Campanas" asp-action="Index">Gestionar Campañas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LOGIC">CampañaLOGIC</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Reporte">Reporte</a>
                            </li>
                        }
                        
                        @if(User.IsInRole("ADMIN") )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Admin usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="KPIs" asp-action="Index">Admin KPIs</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>